### ISSUE TITLE
VM links pointing to Github Repo

### ISSUE THREAD

**Issue by codeZeilen** [squeak-smalltalk/squeak.org#10]
Currently the links to download VMs on http://squeak.org/downloads/ point to the OpenSmalltalk VM repository. I think that makes downloading a VM quite hard for anyone who does not know where to go from the repo.

Is there a particular reason for this?

**Comment by fniephaus** [comment]
I changed the link after we moved the VM to GitHub and I didn't want it to point to bintray. Maybe OSVM's GitHub releases list is a better link? Or how would you solve this?

**Comment by codeZeilen** [comment]
If the GitHub releases list is the source for stable versions of the VM then I think we should use that.

**Comment by fniephaus** [comment]
We tag stable releases, and tags can be turned into GitHub releases with binaries annotated. So yes, I'd say this is better :)
