### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by bertfreudenberg** [squeak-smalltalk/squeak.org#11]
... by way of letsencrypt?

**Comment by krono** [comment]
ys.

**Comment by bertfreudenberg** [comment]
Right now I get an "untrusted" warning on https://files.squeak.org/ - does anybody know what's up with that?

**Comment by krono** [comment]
that's very strange. It should not serve the collaborate via files.
I shall have a look.
Ping me if I don't react soon :)

**Comment by pitwegner** [comment]
When visiting http://squeak.org, you are not automatically redirected to https://squeak.org

**Comment by krono** [comment]
That is as of yet expected.

**Comment by fniephaus** [comment]
I've just enabled redirects to https for squeak.org and files.squeak.org. Please let us know if there are any further issues.
