### ISSUE TITLE
Update html-proof to use caching

### ISSUE THREAD

**Issue by fulldecent** [squeak-smalltalk/squeak.org#14]
This will speed up Travis build time by checking external links only once every 6 weeks.

See implementation discussion at https://github.com/gjtorikian/html-proofer/issues/381#issuecomment-282313548

**Comment by fniephaus** [comment]
The total build time is currently below 2 minutes, and the link checking takes around 40s (see [1]).
Also, we don't update the website every day. So I'd say we currently wouldn't really benefit from this optimization. But thanks a lot for the info!

[1] https://travis-ci.org/squeak-smalltalk/squeak.org/builds/204536748

**Comment by fulldecent** [comment]
Understood, thank you.

I mentioned this because squeak is listed on the html-proof homepage as an example of a good html-proof implementation.

**Comment by fniephaus** [comment]
No worries, thanks a lot again!
