### ISSUE TITLE
squeak.org downloads page points to poor choice of bintray page.

### ISSUE THREAD

**Issue by timrowledge** [squeak-smalltalk/squeak.org#16]
Currently the squeak.org/downloads page 'Virtual Machines' section points to https://bintray.com/opensmalltalk/vm/cog/201705031421#files
Which seems to be a poor choice since it lists only win32 packages. Oddly there is a linked page that seems to list all the packages (in a really difficult to read format) lists all the packages - https://dl.bintray.com/opensmalltalk/vm/

Hopefully there is another page with that list nicely formatted to make sense that we could point to.

**Comment by krono** [comment]
That's my fault, because I canceled the other builds as the latest opensmalltalk-vm changes where windows-only.
This lists all versions: https://bintray.com/opensmalltalk/vm/cog/ but is harder to navigate.

With the next push to opensmalltalk-vm, the listing should be properly populated.

Note that the link is a 'trunk' link and does not imply to be stable or useful for that matter…

**Comment by krono** [comment]
Also, there's this: https://bintray.com/opensmalltalk/vm/cog/#files (but sorted alphabetically)
Or this: https://bintray.com/package/files/opensmalltalk/vm/cog?order=desc&sort=fileLastModified&basePath=&tab=files

But I don't know how stable those are.
Note that the initial link (https://bintray.com/opensmalltalk/vm/cog/201705031421#files)  is actually a redirection from https://bintray.com/opensmalltalk/vm/cog/_latestVersion#files

**Comment by timrowledge** [comment]
Thanks for the rapid response.

What I would love to see is a much easier to follow set of links for people to find various VMs; obviously  the ones included in the current release(s) are very important but the daily build versions can be very important when trying to work out where something broke. There is also a need for some explanation of how the VMs are built, where they come from, where they go, how to contact people and so on. We're having to help several kinds of people that range form a newcomer that finds their VM doesn't work and needs pointing to the release VM (because they found a bintray page in some badly thought out googling) to us old guys that don't know about all this new-fangled web-build stuff. And of course, a properly documented process is helpful when somebody is trying to help you solve a problem several years from now when you can't quite remember what that strange directory is for...
Since I don't actually know how we do the web-builds I can't offer much in the way of example words to improve the Downloads page. Since the Downloads page is quite complex I suggest we don't add a great deal to it directly. If we were to change the 'Virtual Machines' section to
```
The virtual machine (or 'VM') executes Squeak image files on a particular platform. You can download just the VM packages from here - 
OpenSmalltalk VMs (stable released versions) {linky stuff}
Classic VMs {linky stuff}
For the latest 'trunk' development systems please see {link to development page}
```
We'd probably want to add that link to the 'Current Alpha Version' section higher up the page.
This would then leave us to add more information on the Development page, which seems like a good place for it. Somewhere we really need an explanation of what 'squeak.stack.spur' and cog_macos64x64_newspeak.cog.v2_20620230' mean, not to mention the difference to the classic VM and why you might need to use one over the other. After all that, I guess we can explain the whole 

> "source code is generated from an update vmmaker image running on wibblebox.com virtual Cray servers in orbit around Pluto, transmitted to the MrButlerBuilder.org service where it is compiled into executable form and test run via Testicle before being stored on bin-box.co.ch. Versions that pass the basic test are uploaded to possibili.ty which we link to from squeak.org to make them easily available"

 ... thing. Or something like that!

**Comment by krono** [comment]
With the move to GH Actions and releases, this is no longer the case.
