### ISSUE TITLE
http://files.squeak.org/2.2/ is corrupt

### ISSUE THREAD

**Issue by bertfreudenberg** [squeak-smalltalk/squeak.org#22]
http://files.squeak.org/2.2/ shows this:
```
This page contains the following errors:
error on line 13 at column 4982: Encoding error
Below is a rendering of the page up to the first error.
Index of /2.2/
```
(BTW, I had to manually go to the http site in an incognito window because it kept redirecting to https://files.squeak.org/2.2/ which shows the Nextcloud server)

**Comment by krono** [comment]
[close]

On 13.04.2018, at 16:49, Bert Freudenberg <notifications@github.com> wrote:
> 
> http://files.squeak.org/2.2/ shows this:
> 
> This page contains the following errors:
> error on line 13 at column 4982: Encoding error
> Below is a rendering of the page up to the first error.
> Index of /2.2/
> 

Fixed.

> (BTW, I had to manually go to the http site in an incognito window because it kept redirecting to https://files.squeak.org/2.2/ which shows the Nextcloud server)

Does not happen here. do you use HTTPSEverywhere? Which browsers?

Best regards
	-Tobias
