### ISSUE TITLE
mailing list links on squeak.org should point to a mailman archive for now

### ISSUE THREAD

**Issue by pdebruic** [squeak-smalltalk/squeak.org#40]
nabble (operators of forum.world.st) have somehow switched to a forum format and not a mailing list format.  And so people finding and interacting with Squeak Dev there aren't having their messages forwarded to the actual list.  So it makes squeak-dev look like a ghost town.

On this page: https://squeak.org/community/ the links for the mailing lists point to the now broken forum.world.st site.

**Comment by saijanai** [comment]
I noticed this quite some time ago . I sent several messages that no-one ever responded to for the issue you mentioned.

**Comment by ccrraaiigg** [comment]
Where did you send the messages?

**Comment by krono** [comment]
Thanks to all for pointing this out. This was eventually fixed in d9115378ba548dfa3c2b8b51ff07ac12feb92821.
